
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = '\x08\x81\xaa\xd6\x99f\xfc$x\x92~NJg\xaeb'
    
_lr_action_items = {'ASSIGNOP':([4,41,],[8,44,]),'EQOP':([10,14,15,18,20,22,32,34,35,36,37,38,42,43,45,46,48,],[-16,-15,27,27,-6,27,-5,-8,-10,-7,27,-9,27,27,-12,-13,-14,]),'CONST':([6,8,11,13,24,25,26,27,28,39,40,],[10,10,10,10,10,10,10,10,10,10,10,]),'LBRAC':([14,],[23,]),'EXISTS':([6,8,11,13,24,25,26,27,28,39,40,],[9,9,9,9,9,9,9,9,9,9,9,]),'MAINEXP':([0,],[1,]),'VARORDER':([0,],[2,]),'IMPLIESOP':([10,14,15,18,20,22,32,34,35,36,37,38,42,43,45,46,48,],[-16,-15,25,25,-6,25,-5,-8,25,-7,25,-9,25,25,-12,-13,-14,]),'OROP':([10,14,15,18,20,22,32,34,35,36,37,38,42,43,45,46,48,],[-16,-15,24,24,-6,24,-5,-8,24,-7,24,24,24,24,-12,-13,-14,]),'NOTOP':([6,8,11,13,24,25,26,27,28,39,40,],[11,11,11,11,11,11,11,11,11,11,11,]),'COLON':([1,2,16,29,33,],[6,7,-19,-18,41,]),'DOT':([16,19,21,29,],[-19,30,31,-18,]),'LPAREN':([6,8,11,13,24,25,26,27,28,30,31,39,40,],[13,13,13,13,13,13,13,13,13,39,40,13,13,]),'VARIABLE':([0,6,7,8,9,11,12,13,16,23,24,25,26,27,28,39,40,44,],[4,14,16,14,19,14,16,14,16,16,14,14,14,14,14,14,14,16,]),'RPAREN':([10,14,20,22,32,34,35,36,37,38,42,43,45,46,48,],[-16,-15,-6,32,-5,-8,-10,-7,-11,-9,45,46,-12,-13,-14,]),'XOROP':([10,14,15,18,20,22,32,34,35,36,37,38,42,43,45,46,48,],[-16,-15,28,28,-6,28,-5,-8,28,-7,28,-9,28,28,-12,-13,-14,]),'RBRAC':([16,29,47,],[-19,-18,48,]),'ANDOP':([10,14,15,18,20,22,32,34,35,36,37,38,42,43,45,46,48,],[-16,-15,26,26,-6,26,-5,26,26,-7,26,26,26,26,-12,-13,-14,]),'EXISTS_EXCL':([6,8,11,13,24,25,26,27,28,39,40,],[12,12,12,12,12,12,12,12,12,12,12,]),'$end':([0,3,5,10,14,15,16,17,18,20,29,32,34,35,36,37,38,45,46,48,],[-17,0,-4,-16,-15,-3,-19,-1,-2,-6,-18,-5,-8,-10,-7,-11,-9,-12,-13,-14,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'start':([0,],[3,]),'variableList':([7,12,16,23,44,],[17,21,29,33,47,]),'expression':([6,8,11,13,24,25,26,27,28,39,40,],[15,18,20,22,34,35,36,37,38,42,43,]),'empty':([0,],[5,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> start","S'",1,None,None,None),
  ('start -> VARORDER COLON variableList','start',3,'p_start','/home/robbean/Uned/sw/PBL/PBL-master/include/PyBool_std_parse.py',109),
  ('start -> VARIABLE ASSIGNOP expression','start',3,'p_start','/home/robbean/Uned/sw/PBL/PBL-master/include/PyBool_std_parse.py',110),
  ('start -> MAINEXP COLON expression','start',3,'p_start','/home/robbean/Uned/sw/PBL/PBL-master/include/PyBool_std_parse.py',111),
  ('start -> empty','start',1,'p_start','/home/robbean/Uned/sw/PBL/PBL-master/include/PyBool_std_parse.py',112),
  ('expression -> LPAREN expression RPAREN','expression',3,'p_expression_paren','/home/robbean/Uned/sw/PBL/PBL-master/include/PyBool_std_parse.py',138),
  ('expression -> NOTOP expression','expression',2,'p_expression_not','/home/robbean/Uned/sw/PBL/PBL-master/include/PyBool_std_parse.py',142),
  ('expression -> expression ANDOP expression','expression',3,'p_expression_and','/home/robbean/Uned/sw/PBL/PBL-master/include/PyBool_std_parse.py',146),
  ('expression -> expression OROP expression','expression',3,'p_expression_or','/home/robbean/Uned/sw/PBL/PBL-master/include/PyBool_std_parse.py',150),
  ('expression -> expression XOROP expression','expression',3,'p_expression_xor','/home/robbean/Uned/sw/PBL/PBL-master/include/PyBool_std_parse.py',154),
  ('expression -> expression IMPLIESOP expression','expression',3,'p_expression_impl','/home/robbean/Uned/sw/PBL/PBL-master/include/PyBool_std_parse.py',158),
  ('expression -> expression EQOP expression','expression',3,'p_expression_eqv','/home/robbean/Uned/sw/PBL/PBL-master/include/PyBool_std_parse.py',162),
  ('expression -> EXISTS VARIABLE DOT LPAREN expression RPAREN','expression',6,'p_expression_exists','/home/robbean/Uned/sw/PBL/PBL-master/include/PyBool_std_parse.py',166),
  ('expression -> EXISTS_EXCL variableList DOT LPAREN expression RPAREN','expression',6,'p_expression_exists_excl','/home/robbean/Uned/sw/PBL/PBL-master/include/PyBool_std_parse.py',171),
  ('expression -> VARIABLE LBRAC variableList COLON ASSIGNOP variableList RBRAC','expression',7,'p_expression_rename','/home/robbean/Uned/sw/PBL/PBL-master/include/PyBool_std_parse.py',176),
  ('expression -> VARIABLE','expression',1,'p_expression_var','/home/robbean/Uned/sw/PBL/PBL-master/include/PyBool_std_parse.py',188),
  ('expression -> CONST','expression',1,'p_expression_const','/home/robbean/Uned/sw/PBL/PBL-master/include/PyBool_std_parse.py',204),
  ('empty -> <empty>','empty',0,'p_empty','/home/robbean/Uned/sw/PBL/PBL-master/include/PyBool_std_parse.py',212),
  ('variableList -> VARIABLE variableList','variableList',2,'p_variableList','/home/robbean/Uned/sw/PBL/PBL-master/include/PyBool_std_parse.py',218),
  ('variableList -> VARIABLE','variableList',1,'p_variableList','/home/robbean/Uned/sw/PBL/PBL-master/include/PyBool_std_parse.py',219),
]
